### ISSUE TITLE
Make versions of start/stop icons of 16x16 size

### ISSUE THREAD

**Issue by zharro** [matrohin/GitlabEasyTimeTracking#10]
According to https://developer.chrome.com/apps/manifest/icons, Chrome Extension favicon must be 16x16px. Generate such icon versions to use as the extension favicons.

**Comment by matrohin** [comment]
We have svg icons. Isn't it enough?
I thought that we can just add '"16": "play.svg"' to the manifest and it should work fine.

**Comment by matrohin** [comment]
Closing the issue since you moved it to done.
